---
title: "Test time-varying parametric exponential model with OU processes"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
knitr::opts_chunk$set(fig.height = 6, fig.width = 8, out.width = "100%")
knitr::opts_chunk$set(comment = "#>")
options(width = 100)
```

## Load packages, scripts and data

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(cmdstanr)
library(bayesplot)

path_proj <- here::here()
path_src <- file.path(path_proj, "src")
path_models <- file.path(path_src, "models")

source(file.path(path_src, "40-simulate.R"))
source(file.path(path_src, "50-modelling.R"))

model <- cmdstan_model(file.path(path_models, "exp-ou.stan"))
```

## Fully reported scenario

### Setting

```{r}
# data
alpha_increase_seq_1 <- seq(10, 750, by = 30)
alpha_decrease_seq_1 <- seq(750, 10, by = -30)
alpha_lamb <-  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10),
                 alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
                 rep(10,5))
beta_lamb <- 0.5
T <- 60
D <- 15;
```

### Simulation

```{r}
args_exp_ou_fr <- list(
  data = list(
    alpha_lamb = alpha_lamb,
    beta_lamb  = beta_lamb,
    T       = T,
    date_start = as.Date("2024-01-01"),
    D = D
  ),
  q_model = list(
    method        = "exp_ou",
    method_params = list(theta_logb = 0.3, mu_logb = log(0.7), init_logb = log(0.7), sigma_logb = 0.2,
                         theta_logitphi = 0.3, mu_logitphi = 1, init_logitphi = 1, sigma_logitphi = 0.2)
  )
)
exp_ou_fr <- simulateData(args_exp_ou_fr)
par(mfrow = c(2, 1))
plot(exp_ou_fr$b, pch = 19, type = "b")
plot(exp_ou_fr$phi, pch = 19, type = "b")

par(mfrow = c(1, 1))
matplot(t(exp_ou_fr$q), type = "l", lty = 1, ylim = c(0, 1))
```

### Model fitting

```{r}
ind <- 40
hypers <- hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential", alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15)
stan_data <- c(list(T = ind, D = 15, Y = exp_ou_fr$case_reported_cumulated[1:ind, ]), hypers)

test <- model$sample(
    data = stan_data,
    iter_sampling = 3000,
    iter_warmup = 2000,
    chains = 1,
    refresh = 0,
    thin = 1)
varnames <- test$summary()$variable

mcmc_areas(test$draws("sigma_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("sigma_logit_phi"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("theta_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("theta_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test$draws("mu_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("mu_logit_phi"), prob = 0.95, prob_outer = 0.95)


param_true <- tibble(
    parameter = grep("^b\\[.+\\]$", varnames, value = TRUE),
    x = exp_ou_fr$b[1:ind]
)
mcmc_areas(test$draws("b"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true <- tibble(
    parameter = grep("^phi\\[.+\\]$", varnames, value = TRUE),
    x = 1 - exp_ou_fr$phi[1:ind]
)
mcmc_areas(test$draws("phi"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true <- tibble(
    parameter = grep("^lambda\\[.+\\]$", varnames, value = TRUE),
    x = exp_ou_fr$lambda[1:ind]
)
mcmc_areas(test$draws("lambda"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true <- tibble(
    parameter = grep("^q\\[10,.+\\]$", varnames, value = TRUE),
    x = exp_ou_fr$q[10,]
)
mcmc_areas(test$draws(grep("^q\\[10,.+\\]$", varnames, value = TRUE)), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true <- tibble(
    parameter = grep("^N\\[.+\\]$", varnames, value = TRUE),
    x = exp_ou_fr$case_true[1:ind, 1]
)
mcmc_areas(test$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)
```

## Non-fully reported scenario

### Simulation

```{r}
args_exp_ou_nfr <- list(
  data = list(
    alpha_lamb = alpha_lamb,
    beta_lamb  = beta_lamb,
    T       = T,
    date_start = as.Date("2024-01-01"),
    D = D
  ),
  q_model = list(
    method        = "exp_ou",
    method_params = list(theta_logb = 0.2, mu_logb = log(0.2), init_logb = log(0.2), sigma_logb = 0.15,
                         theta_logitphi = 0.2, mu_logitphi = 1.5, init_logitphi = 1.5, sigma_logitphi = 0.15)
  )
)

exp_ou_nfr <- simulateData(args_exp_ou_nfr)
par(mfrow = c(2, 1))
plot(exp_ou_nfr$b, pch = 19, type = "b")
plot(exp_ou_nfr$phi, pch = 19, type = "b")

par(mfrow = c(1, 1))
matplot(t(exp_ou_nfr$q), type = "l", lty = 1, ylim = c(0, 1))
```


### Model fitting

```{r}
ind <- 40
hypers <- hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential", alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15)
stan_data <- c(list(T = ind, D = 15, Y = exp_ou_nfr$case_reported_cumulated[1:ind, ]), hypers)

test <- model$sample(
    data = stan_data,
    iter_sampling = 3000,
    iter_warmup = 3000,
    chains = 1,
    refresh = 0,
    thin = 1)
varnames <- test$summary()$variable

mcmc_areas(test$draws("sigma_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("sigma_logit_phi"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("theta_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("theta_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test$draws("mu_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("mu_logit_phi"), prob = 0.95, prob_outer = 0.95)


param_true <- tibble(
    parameter = grep("^b\\[.+\\]$", varnames, value = TRUE),
    x = exp_ou_nfr$b[1:ind]
)
mcmc_areas(test$draws("b"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true <- tibble(
    parameter = grep("^phi\\[.+\\]$", varnames, value = TRUE),
    x = exp_ou_nfr$phi[1:ind]
)
mcmc_areas(test$draws("phi"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true <- tibble(
    parameter = grep("^lambda\\[.+\\]$", varnames, value = TRUE),
    x = exp_ou_nfr$lambda[1:ind]
)
mcmc_areas(test$draws("lambda"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true <- tibble(
    parameter = grep("^q\\[10,.+\\]$", varnames, value = TRUE),
    x = exp_ou_nfr$q[10,]
)
mcmc_areas(test$draws(grep("^q\\[10,.+\\]$", varnames, value = TRUE)), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true <- tibble(
    parameter = grep("^N\\[.+\\]$", varnames, value = TRUE),
    x = exp_ou_nfr$case_true[1:ind, 1]
)
mcmc_areas(test$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)
```

