---
title: "Sims"
author: "Yang Xiao"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(splines)
library(ggplot2)
library(bayesplot)
library(reshape2)
library(dplyr)
library(aweek)
library(latex2exp)
library(lubridate)

```

# Setting
```{r}
# Set your path first
path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "functions", "simulations_functions.R"))
source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "fit_function.R"))
source(file.path(path_source, "functions", "table_function.R"))

# place for draws
posterior_draws_path = file.path("F:/", "draws")

#data path
data_save_path = file.path(path_proj, "data", "fitted_model", "simulation", "multiSims", "b_constant")
```

```{r}
# models
q_constant <- file.path(path_proj, "source", "models", 
                      "nonparam.stan")
b_constant <- file.path(path_proj, "source", "models", 
                     "exp.stan")
b_rw <- file.path(path_proj, "source", "models", 
                     "exp_rw1.stan")
b_ou <-  file.path(path_proj, "source", "models", 
                      "exp_ou.stan")

compiled_models <- list(
  q_constant = cmdstan_model(q_constant),
  b_constant = cmdstan_model(b_constant),
  b_rw = cmdstan_model(b_rw),
  b_ou = cmdstan_model(b_ou)
)

models_to_use <- c("q_constant", "b_constant", "b_rw", "b_ou")
```

```{r}
###### setting #####
# set seed to replicate
seed <- 123
set.seed(seed)
# data
alpha_increase_seq_1 <- seq(10, 750, by = 30)
alpha_decrease_seq_1 <- seq(750, 10, by = -30)
alpha_lamb =  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10), 
                 alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
                 rep(10,5))
beta_lamb = 0.5
T = 60
# reprot delay
D <- 15;

# Time period for checking
D_check <- 5

# number of simulations
num_sims <- 100

first_date <- as.Date("2024-01-01")

scoreRange <- c(first_date+days(9), first_date+days(19), first_date+days(29),
                first_date+days(39), first_date+days(49))
```

## Fully reported case

### Simulation
```{r}
b_constant_FR_multi <- list()
# generate
for (i in 1:num_sims) {
  b_constant_FR_multi[[i]] <- simulateData(
        params <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    T       = T,
    date_start = first_date,
    D = D
  ),
  q_model = list(
    method        = "b_constant",
    method_params = list(b = 0.7, phi = 0.9)
  )
)
  )
}

plot(b_constant_FR_multi[[1]]$q, col = "red", pch = 19, type = "b", ylim = c(0,1))

```


### Exploratory analysis
```{r}
# exploritary analysis
page_num <- ceiling(nrow(b_constant_FR_multi[[1]]$case_reported_cumulated)/16)
exp_plot_b_constant <- fit_exp_plot(b_constant_FR_multi[[1]]$case_reported_cumulated,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
# print(exp_plot_b_constant)
# 
# exp_plot_b_constant$coefficients
exp_b_data_b_constant<- data.frame( date = as.Date(rownames(b_constant_FR_multi[[1]]$case_reported_cumulated)),
                          b = exp_plot_b_constant$coefficients$b)

exp_b_plot_b_constant <- ggplot(exp_b_data_b_constant, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +       
  geom_smooth(method = "loess", se = TRUE,        
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")

print(exp_b_plot_b_constant)
```


### Model fitting
```{r}
out_b_constant_FR_multi <- list()
for (i in 1:num_sims) {
  print(paste0("Now is working on ",i,"th simulation."))
  out_b_constant_FR_multi[[i]] <-
    nowcasting_moving_window(b_constant_FR_multi[[i]]$case_reported_cumulated, scoreRange =  scoreRange,
                          case_true = b_constant_FR_multi[[i]]$case_true,
                          start_date = first_date,
                          D = D,
                          methods =models_to_use,
                          compiled_models = compiled_models,
                          iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                          num_chains = 3, suppress_output = T,
                          posterior_draws_path = file.path(posterior_draws_path, "b_constant","FR")
                          )
}

save(out_b_constant_FR_multi, file = file.path(data_save_path, "FR_b_constant_multi.RData"))
# load( file.path(data_save_path, "FR_b_constant_multi.RData"))

# Result table to generate metrics
results_b_constant_FR <- compute_all_nowcasts_tables(out_b_constant_FR_multi, D, "day", models_to_use)

save(results_b_constant_FR, file = file.path(data_save_path, "FR_b_constant_multi_result.RData"))
#load( file.path(data_save_path, "FR_b_constant_multi_result.RData"))

# Average metrics
metrics_1_b_constant_FR_avg <- average_nowcasts_metrics(
  results_all   = results_b_constant_FR,
  methods       =  models_to_use,
  filter_length = 15 #nowcasting length
)

metrics_1_b_constant_FR_avg

# Average metrics for most recent days
metrics_1_b_constant_FR_avg_incomp <- average_nowcasts_metrics(
  results_all   = results_b_constant_FR,
  methods       = models_to_use,
  filter_length = D_check
) 
metrics_1_b_constant_FR_avg_incomp

#
results_b_constant_FR_1 <- nowcasts_table(out_b_constant_FR_multi[[1]], D = D, report_unit = "day",
                          methods = models_to_use)

# plots_b_constant_FR <- nowcasts_plot(results_b_constant_FR_1, D = D, report_unit = "day", methods = models_to_use)
# plots_b_constant_FR
```

```{r}
results_b_constant_FR_1 <- nowcasts_table(out_b_constant_FR_multi[[1]], D = D, report_unit = "day", 
                           methods = models_to_use)

names(results_b_constant_FR_1) <- sapply(scoreRange, function(x) TeX(as.character(x), bold = TRUE))

output <- bind_rows(results_b_constant_FR_1, .id = "time_point") |>
  pivot_longer(
    cols = mean_q_constant:upper_b_ou,
    names_to = c(".value", "model"),
    names_pattern = "([a-z]+)_(.+)"
  ) |>
  mutate(model = factor(model,
    levels = c("q_constant", "b_constant", "b_rw", "b_ou"),
    labels = c(
      TeX("M1: Non-parametric $q_d$", bold = TRUE),
      TeX("M2: Parametric $q(d)$", bold = TRUE),
      TeX("M3: $q_t(d)$ with random walks", bold = TRUE),
      TeX("M4: $q_t(d)$ with OU processes", bold = TRUE)))
  )
method_colors <- setNames(c("#008080", "#228B22", "#8446c6", "#4682B4", "gray40", "tomato"),
  c(levels(output$model), "Current reported cases", "Actual cases"))

results_b_constant_FR_1_plots <- ggplot(output) +
  geom_ribbon(aes(x = date, ymin = lower, ymax = upper, fill = model), alpha = 0.4, show.legend = FALSE) +
  geom_line(aes(date, mean, color = model), linewidth = rel(0.4), show.legend = FALSE) +
  geom_line(aes(date, case_reported, color = "Current reported cases"), linewidth = rel(0.4)) +
  geom_point(aes(date, case_reported, color = "Current reported cases"), size = rel(0.5)) +
  geom_line(aes(date, case_true, color = "Actual cases"), linetype = 6) +
  facet_grid(time_point ~ model, labeller = label_parsed, scales = "free") +
  labs(fill = NULL, color = NULL, x = NULL, y = "Number of cases") +
  theme_bw(9) +
  theme(
    legend.position = c(0.88, 0.94),
    legend.key.height = unit(0.4, 'cm'),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  ) +
  scale_fill_manual(values = method_colors[1:4]) +
  scale_color_manual(values = method_colors, breaks = names(method_colors)[5:6])
ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_constant", "FR_b_constant_separated.png"),
       plot = results_b_constant_FR_1_plots,
       width = 8, height = 6, dpi = 300)
```


## Not fully reported case

### Simulation
```{r}
set.seed(seed)
b_constant_NFR_multi <- list()
# generate
for (i in 1:num_sims) {
  b_constant_NFR_multi[[i]] <- simulateData(
        params <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    T       = T,
    date_start = first_date,
    D = D
  ),
  q_model = list(
    method        = "b_constant",
    method_params = list(b = 0.2, phi = 0.9)
  )
)
  )
}

plot(b_constant_NFR_multi[[1]]$q, col = "red", pch = 19, type = "b", ylim = c(0,1))

```

### Exploratory analysis
```{r}
# exploritary analysis
page_num <- ceiling(nrow(b_constant_NFR_multi[[1]]$case_reported_cumulated)/16)
exp_plot_b_constant <- fit_exp_plot(b_constant_NFR_multi[[1]]$case_reported_cumulated,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
# print(exp_plot_b_constant)
# 
# exp_plot_b_constant$coefficients
exp_b_data_b_constant<- data.frame( date = as.Date(rownames(b_constant_NFR_multi[[1]]$case_reported_cumulated)),
                          b = exp_plot_b_constant$coefficients$b)

exp_b_plot_b_constant <- ggplot(exp_b_data_b_constant, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +       
  geom_smooth(method = "loess", se = TRUE,        
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")

print(exp_b_plot_b_constant)
```



### Model fitting
```{r}
out_b_constant_NFR_multi <- list()
for (i in 1:num_sims) {
  print(paste0("Now is working on ",i,"th simulation."))
  out_b_constant_NFR_multi[[i]] <-
    nowcasting_moving_window(b_constant_NFR_multi[[i]]$case_reported_cumulated, scoreRange =  scoreRange,
                          case_true = b_constant_NFR_multi[[i]]$case_true,
                          start_date = first_date,
                          D = D,
                          methods =models_to_use,
                          compiled_models = compiled_models,
                          iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                          num_chains = 3, suppress_output = T,
                          posterior_draws_path = file.path(posterior_draws_path, "b_constant","NFR")
                          )
}

save(out_b_constant_NFR_multi, file = file.path(data_save_path, "NFR_b_constant_multi.RData"))
# load( file.path(data_save_path, "NFR_b_constant_multi.RData"))

# Result table to generate metrics
results_b_constant_NFR <- compute_all_nowcasts_tables(out_b_constant_NFR_multi, D, "day", models_to_use)

save(results_b_constant_NFR, file = file.path(data_save_path, "NFR_b_constant_multi_result.RData"))
# load( file.path(data_save_path, "NFR_b_constant_multi_result.RData"))

# Average metrics
metrics_1_b_constant_NFR_avg <- average_nowcasts_metrics(
  results_all   = results_b_constant_NFR,
  methods       =  models_to_use,
  filter_length = 15 #nowcasting length
)

metrics_1_b_constant_NFR_avg

# Average metrics for most recent days
metrics_1_b_constant_NFR_avg_incomp <- average_nowcasts_metrics(
  results_all   = results_b_constant_NFR,
  methods       = models_to_use,
  filter_length = D_check
) 
metrics_1_b_constant_NFR_avg_incomp

#
results_b_constant_NFR_1 <- nowcasts_table(out_b_constant_NFR_multi[[1]], D = D, report_unit = "day", 
                          methods = models_to_use)

# plots_b_constant_NFR <- nowcasts_plot(results_b_constant_NFR_1, D = D, report_unit = "day", methods = models_to_use)
# plots_b_constant_NFR

```   

```{r}
results_b_constant_NFR_1 <- nowcasts_table(out_b_constant_NFR_multi[[1]], D = D, report_unit = "day", 
                           methods = models_to_use)

names(results_b_constant_NFR_1) <- sapply(scoreRange, function(x) TeX(as.character(x), bold = TRUE))

output <- bind_rows(results_b_constant_NFR_1, .id = "time_point") |>
  pivot_longer(
    cols = mean_q_constant:upper_b_ou,
    names_to = c(".value", "model"),
    names_pattern = "([a-z]+)_(.+)"
  ) |>
  mutate(model = factor(model,
    levels = c("q_constant", "b_constant", "b_rw", "b_ou"),
    labels = c(
      TeX("M1: Non-parametric $q_d$", bold = TRUE),
      TeX("M2: Parametric $q(d)$", bold = TRUE),
      TeX("M3: $q_t(d)$ with random walks", bold = TRUE),
      TeX("M4: $q_t(d)$ with OU processes", bold = TRUE)))
  )
method_colors <- setNames(c("#008080", "#228B22", "#8446c6", "#4682B4", "gray40", "tomato"),
  c(levels(output$model), "Current reported cases", "Actual cases"))

results_b_constant_NFR_1_plots <- ggplot(output) +
  geom_ribbon(aes(x = date, ymin = lower, ymax = upper, fill = model), alpha = 0.4, show.legend = FALSE) +
  geom_line(aes(date, mean, color = model), linewidth = rel(0.4), show.legend = FALSE) +
  geom_line(aes(date, case_reported, color = "Current reported cases"), linewidth = rel(0.4)) +
  geom_point(aes(date, case_reported, color = "Current reported cases"), size = rel(0.5)) +
  geom_line(aes(date, case_true, color = "Actual cases"), linetype = 6) +
  facet_grid(time_point ~ model, labeller = label_parsed, scales = "free") +
  labs(fill = NULL, color = NULL, x = NULL, y = "Number of cases") +
  theme_bw(9) +
  theme(
    legend.position = c(0.88, 0.94),
    legend.key.height = unit(0.4, 'cm'),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  ) +
  scale_fill_manual(values = method_colors[1:4]) +
  scale_color_manual(values = method_colors, breaks = names(method_colors)[5:6])
ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_constant", "NFR_b_constant_separated.png"),
       plot = results_b_constant_NFR_1_plots,
       width = 8, height = 6, dpi = 300)
```



## Result generate

### Metrics table
```{r}
model_names <- c("M1: Non-paramatric $q_d$", 
                 "M2: Paramatric $q(d)$", 
                 "M3: Time-varying $q_t(d)$ - RW", 
                 "M4: Time-varying $q_t(d)$ - OU")


highlight_metrics(metrics_1_b_constant_FR_avg, model_names = model_names,
                  D = D, first_date = first_date, date_labels = scoreRange,
                  scenario_names = c("Initial","Increasing","Peak","Decreasing","Final"),
                  table_caption = "Fully Reported + Constant b (All nowcast window)",
                  report_scenario = "fr", model_origin = "constant")


print(model_names)

highlight_metrics(metrics_1_b_constant_FR_avg_incomp,
                  model_names = model_names,
                  scenario_names = c("Initial","Increasing","Peak","Decreasing","Final"),
                  D = D, first_date = first_date, date_labels = scoreRange,
                  table_caption = "Fully Reported + Constant b (Last 5 days)",
                   report_scenario = "fr", model_origin = "constant")
```

```{r}
highlight_metrics(metrics_1_b_constant_NFR_avg, model_names = model_names,
                  D = D, first_date = first_date, date_labels = scoreRange,
                  scenario_names = c("Initial","Increasing","Peak","Decreasing","Final"),
                  table_caption = "Not Fully Reported + Constant b (All nowcast window)",
                  report_scenario = "nfr", model_origin = "constant")
highlight_metrics(metrics_1_b_constant_NFR_avg_incomp,
                  model_names = model_names,
                  scenario_names = c("Initial","Increasing","Peak","Decreasing","Final"),
                  D = D, first_date = first_date, date_labels = scoreRange,
                  table_caption = "Not Fully Reported + Constant b (Last 5 days)",
                   report_scenario = "nfr", model_origin = "constant")
```

### Plots
```{r}
# plots_b_constant_FR <- nowcasts_plot(results_b_constant_FR_1, D = D, report_unit = "day", methods = models_to_use,
#                                   combine_plots = T, ncol=1, nrow = 5)
# 
# ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_constant", "FR_b_constant.png"),
#        plot = plots_b_constant_FR,
#        width = 10, height = 18, dpi = 300)


plots_b_constant_FR_separated <- nowcasts_plot_separated(results_b_constant_FR_1, D = D, report_unit = "day", methods = models_to_use, combine_plots = T)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_constant", "FR_b_constant_separated.png"),
       plot = plots_b_constant_FR_separated,
       width = 40, height = 28, dpi = 300)
```

```{r}
# plots_b_constant_NFR <- nowcasts_plot(results_b_constant_NFR, D = D, report_unit = "day", methods = models_to_use,
#                                   combine_plots = T, ncol=1, nrow = 5)
# 
# ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_constant", "NFR_b_constant.png"),
#        plot = plots_b_constant_NFR,
#        width = 10, height = 16, dpi = 300)

plots_b_constant_NFR_separated <- nowcasts_plot_separated(results_b_constant_NFR_1, D = D, report_unit = "day", methods = models_to_use, combine_plots = T)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_constant", "NFR_b_constant_separated.png"),
       plot = plots_b_constant_NFR_separated,
       width = 40, height = 28, dpi = 300)
```




